<?php 
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_trabalhos',
		'title' => '[:pb]Trabalhos[:]',
		'fields' => array (
			array (
				'key' => 'field_57d3322d34e85',
				'label' => 'Fonte do titulo Trilhas',
				'name' => 'fonte_trilhas',
				'type' => 'google_font_selector',
				'instructions' => 'Fonte do título trilhas',
				'include_web_safe_fonts' => 1,
				'enqueue_font' => 1,
				'default_font' => 'Droid Sans',
			),
			array (
				'key' => 'field_57d35585c63a5',
				'label' => 'Tamanho da fonte Trilhas',
				'name' => 'tamanho_trilhas',
				'type' => 'number',
				'default_value' => 40,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_57d373f3cfd76',
				'label' => 'Cor da fonte Trilhas',
				'name' => 'cor_trilhas',
				'type' => 'color_picker',
				'default_value' => '#000',
			),
			array (
				'key' => 'field_57d3322e34e86',
				'label' => 'Fonte do título SoundArt',
				'name' => 'fonte_soundart',
				'type' => 'google_font_selector',
				'instructions' => 'Fonte do título soundart',
				'include_web_safe_fonts' => 1,
				'enqueue_font' => 1,
				'default_font' => 'Droid Sans',
			),
			array (
				'key' => 'field_57d355aec63a6',
				'label' => 'Tamanho da fonte soundart',
				'name' => 'tamanho_soundart',
				'type' => 'number',
				'default_value' => 40,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_57d3742fcfd77',
				'label' => 'Cor da fonte soundart',
				'name' => 'cor_soundart',
				'type' => 'color_picker',
				'default_value' => '#000',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-trabalhos.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_blog',
		'title' => 'Blog',
		'fields' => array (
			array (
				'key' => 'field_57c4f8de202d4',
				'label' => 'fundo',
				'name' => 'fundo',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_57c4fa9554cca',
				'label' => 'repetir imagem',
				'name' => 'repetir_imagem',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-blog.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-ritaleena.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_linda',
		'title' => 'Linda',
		'fields' => array (
			array (
				'key' => 'field_58dad6fee05f3',
				'label' => 'link da matéria',
				'name' => 'link_da_materia',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),			
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-linda.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'send-trackbacks',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'categories',
				11 => 'tags',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_soundart-ou-trilha',
		'title' => 'Soundart ou Trilha',
		'fields' => array (
			array (
				'key' => 'field_57c4b015a3e4b',
				'label' => 'Fonte do título',
				'name' => 'fonte_do_titulo',
				'type' => 'google_font_selector',
				'include_web_safe_fonts' => 0,
				'enqueue_font' => 0,
				'default_font' => 'Kumar One',
			),
			array (
				'key' => 'field_57c4b02ffb6cc',
				'label' => 'Cor do título',
				'name' => 'cor_do_titulo',
				'type' => 'color_picker',
				'default_value' => '',
			),
			array (
				'key' => 'field_57c4b058fb6cd',
				'label' => 'Cor do fundo da fonte',
				'name' => 'cor_do_fundo_da_fonte',
				'type' => 'color_picker',
				'default_value' => '#048637',
			),
			array (
				'key' => 'field_57d5d3c1b1861',
				'label' => 'Tamanho da fonte do titulo',
				'name' => 'tamanho',
				'type' => 'number',
				'default_value' => 28,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_57d5f2d1ccce7',
				'label' => 'opacidade do fundo',
				'name' => 'opacidade',
				'type' => 'number',
				'default_value' => '0.6',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'soundart',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'trilha',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-ritaleena.php',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 3,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-blog.php',
					'order_no' => 0,
					'group_no' => 4,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'custom_fields',
				2 => 'revisions',
				3 => 'slug',
				4 => 'author',
				5 => 'format',
				6 => 'categories',
				7 => 'tags',
				8 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
